apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass1 # Required. Name your storageclass.
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=performance1" # Required. Corresponds to the labels in the virtual pool.
  fsType: "ext4" # Optional. You can choose to enter ext4 (default), xfs, or ext3.
allowVolumeExpansion: true